oasis:
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: "Bearer "
    refresh-token-expire-time: 2592000000
    key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALs9JPD+rslWA0wek4Q1irp/D1t0ocaUzLVnT3yyvO460TWTF8CRiyOzyU/c2Jb2M0ZC80oXxHpxtNMRNlGgXw0CAwEAAQ=="
    refresh-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM5fx+Y+V0WtOUTHyVj6oYo8V7P7sPwMz85p656BHF+Y9/Ao9jX/CFd/4+JxCnUZut3OyfgCYhSfIEVXiTv7Cx8CAwEAAQ=="
  admin:
    userName: admin
    roles:
     - Admin
server:
  port: 8081
########################################################################
#######                     Mybatis Plus 配置                     #######
########################################################################
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.oasis.common.entity
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oasis_gateway?useSSL=true&requireSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: OasisHikariCP
      connection-test-query: SELECT 1