oasis:
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: "Bearer "
    refresh-token-expire-time: 2592000000
    key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALs9JPD+rslWA0wek4Q1irp/D1t0ocaUzLVnT3yyvO460TWTF8CRiyOzyU/c2Jb2M0ZC80oXxHpxtNMRNlGgXw0CAwEAAQ=="
    refresh-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAM5fx+Y+V0WtOUTHyVj6oYo8V7P7sPwMz85p656BHF+Y9/Ao9jX/CFd/4+JxCnUZut3OyfgCYhSfIEVXiTv7Cx8CAwEAAQ=="
  admin:
    userName: admin
    roles:
     - Admin